### GOODLUCK ###
POST http://localhost:4000/register
Content-Type: application/json

{
  "username": "MihaelJ",
  "password": "Michael11",
  "name": "Michael James",
  "age":"34",
  "gender":"male"
}
###

POST http://localhost:4000/login
Content-Type: application/json

{
  "username": "MihaelJ",
  "password": "Michael11"
}
###

POST http://localhost:4000/issueVisitorPass
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NTg4N2EwZmM5YmY1YTFkNDkyZjM5YjUiLCJ1c2VybmFtZSI6Ik1paGFlbEoiLCJwYXNzd29yZCI6Ik1pY2hhZWwxMSIsIm5hbWUiOiJNaWNoYWVsIEphbWVzIiwiYWdlIjoiMzQiLCJnZW5kZXIiOiJtYWxlIiwiaWF0IjoxNzAzNTA1NjgxfQ.q5R7k25ZC6I9T1-aCX1EKagnQ-LmUuupDreQrykd4QA
Content-Type: application/json

{
  
  "visitorId": "011",
  "name": "Maria George"
}
###

GET http://localhost:4000/visitors
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NDlhNDQ2ZGM1OTA0ZWE0NDdmM2FhZGIiLCJ1c2VybmFtZSI6Ik1pa2F5bGEiLCJwYXNzd29yZCI6IktheWxhMTIzIiwiaWF0IjoxNjg3ODMyNDAyfQ.Y1d8y_KJKQGBUvBJQNpczMLWnYtZGNfsjGRlhb7mZj0
Content-Type: application/json
###

POST http://localhost:4000/visitor/login
Content-Type: application/json

{
  "username": "Maria",
  "password": "MariaG12"
}
###

GET http://localhost:4000/visitor/retrievepass
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Ik1hcmlhIiwicGFzc3dvcmQiOiJNYXJpYUcxMiIsImlhdCI6MTcwMzUwNTg0M30.SfrZ-JNMxekjkv-mXWcqZaArtJhMnaQRxjUwOn2RbVo
Content-Type: application/json
###
GET https://prisonvms.azurewebsites.net/loginpage
Content-Type: application/json
###


















GET https://prisonvms.azurewebsites.net/admindetails
Content-Type: application/json
###




 
###
POST http://localhost:3000/createvisitorData
Content-Type: application/json
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NDlhNDQ2ZGM1OTA0ZWE0NDdmM2FhZGIiLCJ1c2VybmFtZSI6Ik1pa2F5bGEiLCJwYXNzd29yZCI6IktheWxhMTIzIiwiaWF0IjoxNjg3ODMyNDAyfQ.Y1d8y_KJKQGBUvBJQNpczMLWnYtZGNfsjGRlhb7mZj0

{
    "username":"Maria",
    "password": "MariaG12",
    "name": "Maria George",
    "city": "Melbourne",
    "relationship": "Aunt",
    "visitorId": "011"
  
}
###


PATCH  https://prisonvms.azurewebsites.net/649a476a418f91102380abe6
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NDk3Mzc5YjI0OWQ5ZTNmYzdlZDQ4ZTUiLCJ1c2VybmFtZSI6Ik1pa2F5bGEiLCJwYXNzd29yZCI6IktheWxhMTIzIiwiaWF0IjoxNjg3NjM1MDg1fQ.XP_Lhl8zP_LQW_edNNcHH6xG950qsnJAOTquu0Qo9ek

{
  "city": "Texas"
}

###
DELETE  https://prisonvms.azurewebsites.net/649a476a418f91102380abe6
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NDk3Mzc5YjI0OWQ5ZTNmYzdlZDQ4ZTUiLCJ1c2VybmFtZSI6Ik1pa2F5bGEiLCJwYXNzd29yZCI6IktheWxhMTIzIiwiaWF0IjoxNjg3NjM1MDg1fQ.XP_Lhl8zP_LQW_edNNcHH6xG950qsnJAOTquu0Qo9ek
###

GET https://prisonvms.azurewebsites.net/admins
Content-Type: application/json
###


GET https://prisonvms.azurewebsites.net/prisoner
Content-Type: application/json
###

GET https://prisonvms.azurewebsites.net/cell
Content-Type: application/json
###

GET https://prisonvms.azurewebsites.net/emergency
Content-Type: application/json
###

GET https://prisonvms.azurewebsites.net/casedetail
Content-Type: application/json
###