### GOODLUCK ###
### Security Registration ###
POST http://localhost:3000/registerSecurity
Content-Type: application/json

{
  "username": "John",
  "password": "John12",
  "name": "John Noah",
  "age": "30",
  "gender": "male"
}

### Host Registration ###
POST http://localhost:3000/registerHost
Content-Type: application/json

{
  "username": "Arthur",
  "password": "Arthur53",
  "name": "Arthur King",
  "age": "45",
  "gender": "male",
  "contactNum": "076542398",
  "role": "host"
}

###Admin Registration###
POST http://localhost:3000/registerAdmin
Content-Type: application/json

{
  "username": "TroySam",
  "password": "Troy11",
  "name": "Troy Joseph Sam",
  "age": "2",
  "gender": "male"
}

### Host Login ###
POST http://localhost:3000/loginHost
Content-Type: application/json

{
  "username": "Danya",
  "password": "Dan11"
}

### Security Login ###
POST http://localhost:3000/loginSecurity
Content-Type: application/json

{
  "username": "MichaelJ",
  "password": "Michael11"
}


### Admin Login ###
POST http://localhost:3000/loginAdmin
Content-Type: application/json

{
  "username": "TroySam",
  "password": "Troy11"
}
###

### Security Approval for Host Registration ###
POST http://localhost:3000/securityApproval
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NTkxMjMwZDFhYWZkNzQ4ZDJiNTQ3MWUiLCJ1c2VybmFtZSI6Ik1pY2hhZWxKIiwicGFzc3dvcmQiOiJNaWNoYWVsMTEiLCJuYW1lIjoiTWljaGFlbCBKYW1lcyIsImFnZSI6IjM0IiwiZ2VuZGVyIjoibWFsZSIsInJvbGUiOiJzZWN1cml0eSIsImFwcHJvdmFsU3RhdHVzIjp0cnVlLCJpYXQiOjE3MDQwMjUxMTR9.EwLb6ooV3Uvci5lWZB3JkC14a4ooOcHpQKcsE2EXHN4
x-session-identifier: Session_1704025114076_135
Content-Type: application/json

{
  "username": "Arthur"
}



### Issue Visitor Pass ###
POST http://localhost:3000/issueVisitorPass
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NTkxNWJmYjhlN2ZmMDg5NmM4OWQwZmYiLCJ1c2VybmFtZSI6IkRhbnlhIiwicGFzc3dvcmQiOiJEYW4xMSIsIm5hbWUiOiJEYW55YSBKYW1lcyIsImFnZSI6IjMwIiwiZ2VuZGVyIjoiZmVtYWxlIiwiY29udGFjdE51bSI6IjA3NDUzMjQ4OCIsInJvbGUiOiJob3N0IiwiYXBwcm92YWxTdGF0dXMiOnRydWUsImlhdCI6MTcwNDA5ODIzNH0.RfSlU59SfqmHP9_S_LyrS670SsQCGL1Eg5QtocJMG3E
x-session-identifier: Session_1704098234264_98
Content-Type: application/json

{
  "visitorId": "002",
  "name": "mary parker"
}

### Get Visitors ###
GET http://localhost:3000/viewvisitors
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NTkxMmNlNzQ0NWViNjU0ZTFjMGRmYWQiLCJ1c2VybmFtZSI6IkRhbnlhIiwicGFzc3dvcmQiOiJEYW4xMSIsIm5hbWUiOiJEYW55YSBKYW1lcyIsImFnZSI6IjMwIiwiZ2VuZGVyIjoiZmVtYWxlIiwicm9sZSI6Imhvc3QiLCJhcHByb3ZhbFN0YXR1cyI6dHJ1ZSwiYXBwcm92ZWQiOnRydWUsImlhdCI6MTcwNDAxNDUzN30.0A1Gvm9MuAwLuHyV2wH9cpTKAYHmnG0IMZ01nPs6hTw
x-session-identifier: Session_1704014537176_510
Content-Type: application/json


### Retrieve Visitor Pass ###
POST http://localhost:3000/retrievepass
Content-Type: application/json

{
  "visitorId": "002"
}


POST http://localhost:3000/getHostContactNumber
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IlRyb3lTYW0iLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE3MDQxMDg5NzJ9.oCu9iebiD0Yv8NarH65-re6Z16k7KxPiShlBIJ6Qv-U</p>
x-session-identifier: Session_1704098582840_741

{
  "visitorPass": "VP1704098277114869"
}

###view user roles###
GET http://localhost:3000/65915bfb8e7ff0896c89d0ff
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IlRyb3lTYW0iLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE3MDQxMDI5Nzh9.mZZEJTYOjTjo64g7t6aeXnfkiZATEYko8V-NmOV_Fbs
x-session-identifier: Session_1704105924849_138

###edit user roles###
PUT http://localhost:3000/65915bfb8e7ff0896c89d0ff
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IlRyb3lTYW0iLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE3MDQxMDg5NzJ9.oCu9iebiD0Yv8NarH65-re6Z16k7KxPiShlBIJ6Qv-U
x-session-identifier: Session_1704108972224_164

{
  "role": "Host"
}

###swagger page###
GET https://prisonvms.azurewebsites.net/api-docs
Content-Type: application/json
###

###create new visitor###
POST http://localhost:3000/createvisitorData
Content-Type: application/json
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NDlhNDQ2ZGM1OTA0ZWE0NDdmM2FhZGIiLCJ1c2VybmFtZSI6Ik1pa2F5bGEiLCJwYXNzd29yZCI6IktheWxhMTIzIiwiaWF0IjoxNjg3ODMyNDAyfQ.Y1d8y_KJKQGBUvBJQNpczMLWnYtZGNfsjGRlhb7mZj0

{
    "username":"Maria",
    "password": "MariaG12",
    "name": "Maria George",
    "city": "Melbourne",
    "relationship": "Aunt",
    "visitorId": "011"
  
}
###

