### GOODLUCK ###
POST https://prisonvms.azurewebsites.net/register
Content-Type: application/json

{
  "username": "Mikayla",
  "password": "Kayla123"
}
###

GET https://prisonvms.azurewebsites.net/loginpage
Content-Type: application/json
###

POST https://prisonvms.azurewebsites.net/login
Content-Type: application/json

{
  "username": "Mikayla",
  "password": "Kayla123"
}
###

GET https://prisonvms.azurewebsites.net/admindetails
Content-Type: application/json
###

POST https://prisonvms.azurewebsites.net/issueVisitorPass
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NDlhNDQ2ZGM1OTA0ZWE0NDdmM2FhZGIiLCJ1c2VybmFtZSI6Ik1pa2F5bGEiLCJwYXNzd29yZCI6IktheWxhMTIzIiwiaWF0IjoxNjg3ODMyNDAyfQ.Y1d8y_KJKQGBUvBJQNpczMLWnYtZGNfsjGRlhb7mZj0
Content-Type: application/json

{
  
  "visitorId": "009",
  "name": "Sarah Jose"
}
###


GET https://prisonvms.azurewebsites.net/pass
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IlNhcmFoSiIsInJvbGUiOiJ2aXNpdG9yIiwiaWF0IjoxNzAzNDMwMTEwfQ.a1pzMtDzN0Ne8HCPRYLd2PKJ41hlT8HhMbGl4hI-72Q
Content-Type: application/json
###
 
###
POST https://prisonvms.azurewebsites.net/createvisitorData
Content-Type: application/json
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NDlhNDQ2ZGM1OTA0ZWE0NDdmM2FhZGIiLCJ1c2VybmFtZSI6Ik1pa2F5bGEiLCJwYXNzd29yZCI6IktheWxhMTIzIiwiaWF0IjoxNjg3ODMyNDAyfQ.Y1d8y_KJKQGBUvBJQNpczMLWnYtZGNfsjGRlhb7mZj0

{
    "username":"SarahJ",
    "password": "SJ123",
    "name": "Sarah Jose",
    "city": "Melbourne",
    "relationship": "aunt",
    "visitorId": "009"
  
}
###
POST https://prisonvms.azurewebsites.net/visitor/login
Content-Type: application/json

{
  "username": "SarahJ",
  "password": "SJ123"
}
###

PATCH  https://prisonvms.azurewebsites.net/649a476a418f91102380abe6
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NDk3Mzc5YjI0OWQ5ZTNmYzdlZDQ4ZTUiLCJ1c2VybmFtZSI6Ik1pa2F5bGEiLCJwYXNzd29yZCI6IktheWxhMTIzIiwiaWF0IjoxNjg3NjM1MDg1fQ.XP_Lhl8zP_LQW_edNNcHH6xG950qsnJAOTquu0Qo9ek

{
  "city": "Texas"
}

###
DELETE  https://prisonvms.azurewebsites.net/649a476a418f91102380abe6
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NDk3Mzc5YjI0OWQ5ZTNmYzdlZDQ4ZTUiLCJ1c2VybmFtZSI6Ik1pa2F5bGEiLCJwYXNzd29yZCI6IktheWxhMTIzIiwiaWF0IjoxNjg3NjM1MDg1fQ.XP_Lhl8zP_LQW_edNNcHH6xG950qsnJAOTquu0Qo9ek
###

GET https://prisonvms.azurewebsites.net/admins
Content-Type: application/json
###

GET https://prisonvms.azurewebsites.net/visitors
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NDlhNDQ2ZGM1OTA0ZWE0NDdmM2FhZGIiLCJ1c2VybmFtZSI6Ik1pa2F5bGEiLCJwYXNzd29yZCI6IktheWxhMTIzIiwiaWF0IjoxNjg3ODMyNDAyfQ.Y1d8y_KJKQGBUvBJQNpczMLWnYtZGNfsjGRlhb7mZj0
Content-Type: application/json
###

GET https://prisonvms.azurewebsites.net/prisoner
Content-Type: application/json
###

GET https://prisonvms.azurewebsites.net/cell
Content-Type: application/json
###

GET https://prisonvms.azurewebsites.net/emergency
Content-Type: application/json
###

GET https://prisonvms.azurewebsites.net/casedetail
Content-Type: application/json
###